### ISSUE TITLE
forums

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/udacity-course#113]
I know this isn't the code, but is there supposed to be a udacity forum?
Thanks

**Comment by maryx** [comment]
We're looking into this and will update you soon! Thanks for noticing!

**Comment by maryx** [comment]
The forum is located at https://discussions.udacity.com/c/standalone-courses/native-mobile-apps-flutter. Hope that helps!

**Comment by neiljaywarner** [comment]
thanks

**Comment by neiljaywarner** [comment]
actually, the link is giving a 502.
I know that's not on you, it's on udacity, but it is awkward timing.

**Comment by neiljaywarner** [comment]
@maryx  this link still gives the below 
{
	"status": 502,
	"error": {
		"message": "[{Message:no \"data\" or \"errors\" in response from origin}]"
	}
}

**Comment by maryx** [comment]
Hm, what happens if you navigate from the link to the forums in "Have questions? Head to the forums for discussion with the Udacity Community."?

Or if you go to https://discussions.udacity.com/ and then click on the `Build Native Apps with Flutter` course? Just verifying that you had been logged in prior to accessing the page.

**Comment by maryx** [comment]
@neiljaywarner were you able to resolve this issue?

**Comment by neiljaywarner** [comment]
Yes, thank you, sorry about the delay.

It is kinda not cool that you get that error instead of a "please login page" but anyway, if i'm logged in then it's all good with the links (both)

**Comment by maryx** [comment]
Thanks for filing this. I've filed an issue with Udacity; hopefully this will be a better experience in the future!
