### ISSUE TITLE
The Constructor of Cateogry , As per dart documentation it is not understandable.

### ISSUE THREAD

**Issue by gaurav1999** [flutter/udacity-course#117]
Hello Everyone,
I am new to flutter , I was going through the code and I find the const Category() constructor not understandable , 
First , what is the role of key in this ?
Second , why did we used curly braces inside the constructor , 
Third , how assert works here ?

Please give more comments on this part.

**Comment by Sfshaza** [comment]
Hi @gaurav1999, can you give us a link to the page in question?  Thx

**Comment by Sfshaza** [comment]
Wait, I see it's the Udacity course. Can you tell us where it is in the video?  Thanks.

**Comment by Sfshaza** [comment]
(Closed by accident.)

**Comment by maryx** [comment]
@Sfshaza This is likely referring to https://github.com/flutter/udacity-course/blob/master/course/02_category_widget/solution_02_category_widget/lib/category.dart, whose final state is https://github.com/flutter/udacity-course/blob/master/unit_converter/unit_converter/lib/category.dart in the completed app.

@gaurav1999 Please verify!

 1) You can read about keys at https://flutter.io/widgets-intro/#global-keys. At this point, it's probably not strictly necessary.
 2) The curly braces let you define the name for the input parameters. When you instantiate a Category, you can say `var category = Category(name: 'Hello!', ...)` rather than `var category = Category('Hello', ...)`
 3) The assert helps check your input. For instance, if you don't want to allow values to be null, or if you want your input to always be a positive number, etc.

**Comment by gaurav1999** [comment]
Yes It's from category.dart

**Comment by gaurav1999** [comment]
@Sfshaza , thanks a lot for your reply , I understand the concept clearly because of it. But it would be really helpful of you can please elaborate the synatx of the const Category ()  constructor used here , and also if you can provide alternative solution for it ? 
Thanks & Regards
Gaurav Agrawal

**Comment by neiljaywarner** [comment]
@maryx can you please edit your comment above just in case?
this mentions curly braces but there aren't any curly braces.  I was also confused by the curly braces, coming from Kotlin... 
maybe even discussion in video, or at least some code comments, yes, would be nice
--
The curly braces let you define the name for the input parameters. When you instantiate a Category, you can say var category = Category(name: 'Hello!', ...) rather than var category = Category('Hello', ...)

**Comment by maryx** [comment]
@gaurav1999 https://www.dartlang.org/guides/language/language-tour#final-and-const has some explanation of why we use const, and this may help too: https://www.dartlang.org/guides/language/language-tour#using-parameterized-types-with-constructors
Once you've instantiated an instance of the Category widget, it is immutable.

I'm not sure what alternative you're be looking for - it depends on what your use case is.

@neiljaywarner 
The curly braces are in the class constructor like this:
```
  const Category({
    @required this.name,
    @required this.color,
    @required this.iconLocation,
  }) ...
```
Later, when you want to create an instance, you'd do:
```
var category = Category(
  name: 'Hello!',
  color: Colors.red,
  iconLocation: Icons.close,
) 
```
You could have done (without curly braces):
```
const Category(this.name, this.color, this.iconLocation)
```
in which case later when you create an instance, you'd do:
```
var category = Category('Hello!', Colors.red, Icons.close)
```
This is generally less easy to read.

**Comment by maryx** [comment]
If you're happy with the response feel free to close this issue or let me know and I can close it.
