### ISSUE TITLE
Category_route , udacity-course , Is there any way to create List of Icon objects ?

### ISSUE THREAD

**Issue by gaurav1999** [flutter/udacity-course#119]
Hello Everyone .
In the  /course/03_category_route /solution_03_category_route/category_route.dart
We used list of objects which we needed for out listview , for example:-
static const _baseColors = <Color>[
    Colors.teal,
    Colors.orange,
    Colors.pinkAccent,
    Colors.blueAccent,
    Colors.yellow,
    Colors.greenAccent,
    Colors.purpleAccent,
    Colors.red,
  ];

I tried using the same for Icons as an experiment , but it seems that this is not supported.
So is there any other way around of doing so ?

Thanks.

**Comment by maryx** [comment]
Hi @gaurav1999, what have you tried so far? :)

If you think the question is generic enough for [StackOverflow](https://stackoverflow.com/search?q=flutter), you can also consider posting on there with the #flutter tag (also with your code attempts).

**Comment by gaurav1999** [comment]
I tried it , @maryx ,
I used:-
static const _iconlist = [
Icons.cake,
Icons.ac_unit,
//More code
];

Also Sir , now I understand , I will post questions on stackoverflow from now on , I was posting them here because this is the course repository and I thought this would be more relevant here.

Thanks.

**Comment by maryx** [comment]
You can definitely post questions here, but if you think your question is a generic Flutter question, rather than a bug in the course code, you may get faster responses on StackOverflow.

What error/logs did you get with that code? I tried what you had and it seems to be working fine. Does your Icon widget code look like this: `Icon(_iconlist[0])` ?

**Comment by gaurav1999** [comment]
No It doesn't look like that , I shared the example of what I did , I use VS code with flutter extension and it said that what I was doing is wrong , I mean it gave error lines around my code. Currently I don't have any logs/error . Sorry

**Comment by maryx** [comment]
What happens when you try building (green play button) onto a device or emulator? Usually, there will be some errors in the console in the app fails to build. That can help you debug. 
Also, if you hover over the red lines, an error message usually pops up saying why it is red.
It's possible that when you first write the code, it appears to have red lines, but once you build it, it cleans up.

You create the iconlist (your code). Then you want to use the iconlist in your app (e.g. by creating an Icon widget) (my code).

**Comment by gaurav1999** [comment]
Yes I tried It again and this worked , maybe there were some issues in the plugin itself.
I ignored those red lines and build it.
Thank you.
